### ISSUE TITLE
Improve the Readme.md

### ISSUE THREAD

**Issue by ghost** [electron0zero/Ingenuity2017#16]
It should contain the following:-
* Name of the repository
* Purpose
* What is Ingenuity ?
* When is it ?
* Active contributors to this repository with their avatars and github profile links

**Comment by mrinalpande** [comment]
Nai nai hogi readme improve

**Comment by mrinalpande** [comment]
Let's work on the site first.

**Comment by GeekyShiva** [comment]
Done @harshitbudhraja ....thanks mate for the suggestion hope the repo looks good now
