### ISSUE TITLE
sponsors_list

### ISSUE THREAD

**Issue by Shubham-112** [electron0zero/Ingenuity2017#23]
Auto-scroll effect of sponsors was better than the current one because as the number of sponsors increases it will increase the section size.

**Comment by electron0zero** [comment]
@Shubham-112 I can't understand what you mean by this issue, have a look on [how to write a good GitHub issue](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)

please provide more detail on what is the problem?

**Comment by mrinalpande** [comment]
Auto scroll was too small a thing. Also people wanted this as there were differences in sponsors and they are arranged in those differences.

**Comment by GeekyShiva** [comment]
Present scheme of sponsors is good as per the requirement of the of Team ingenuity @Shubham-112 , previous design was too native and change is acceptable per say

the previous scroll effect can't cater the difference in logo sizes isue
